version: '3'

services:
  setup:
    build: .
    command: sh -c 'docker-compose -f /mnt/docker-compose.yml up -d nginx'
    volumes:
      - ./docker-compose.yml:/mnt/docker-compose.yml
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
