# This playbook should be used to run customized webpage, which should be stored in /webroot/index.html

---
- name: deploy nginx on container
  hosts: all # write localhost if you only want to execute the playbook against the localhost
  become: true
  vars:
    webroot: "/webroot"
  tasks:

    # Task 1: ensure system packages are present
    - name: system packages present
      ansible.builtin.apt:
        name:
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    # Task 2: install Docker Module for Python
    - name: Docker Module for Python
      ansible.builtin.pip:
        name: docker

    # Task 3: pull Docker image
    - name: pull nginx image
      community.docker.docker_image:
        name: nginx 
        source: pull
        tag: latest

    # Task 4: Ensure webroot directory exists
    - name: webroot present
      ansible.builtin.file:
        path: "{{ webroot }}"
        state: directory

    # Task 5: Set permissions for the webroot directory
    - name: set permissions for webroot directory
      ansible.builtin.file:
        path: "{{ webroot }}"
        owner: "ubuntu"
        group: "ubuntu"
        mode: "0755"

    # Task 6: run nginx container
    - name: run nginx container
      community.docker.docker_container:
        name: webserver
        image: nginx
        state: started
        detach: true
        exposed_ports:
          - 80
        ports:
          - 8000:80
        volumes:
          - "{{ webroot }}:/usr/share/nginx/html"
